<?php

namespace borpheus\utils;

use yii\widgets\LinkPager;
use yii\helpers\Html;

class TaskForcePagination extends LinkPager
{
    public $prevPageLabel = '';
    public $nextPageLabel = '';
    public $options = ['class' => 'pagination-list'];

    public function init()
    {
        parent::init();
        // здесь вы можете настроить свои стили и т.д.
    }

    public function beforeRun()
    {
        echo '<div class="pagination-wrapper">';
        return parent::beforeRun(); // TODO: Change the autogenerated stub
    }

    public function afterRun($result)
    {
        echo '</div>';
        return parent::afterRun($result); // TODO: Change the autogenerated stub
    }

    protected function renderPageButton($label, $page, $class, $disabled, $active)
    {
        $linkWrapTag = 'li';
        $options = ['class' => 'pagination-item'];
        $linkOptions = ['class' => 'link link--page'];

        if ($active) {
            Html::addCssClass($options, 'pagination-item--active');
        }

        if ($disabled) {
            Html::addCssClass($options, 'pagination-item--disabled');
        }

        if ($label === '') {
            Html::addCssClass($options, 'pagination-item mark');
        }

        return Html::tag($linkWrapTag, Html::a($label, $this->pagination->createUrl($page), $linkOptions), $options);
    }
}